on:
  workflow_dispatch:

jobs:
  provstatus:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: "Provider Status"
    steps:
      - name: Check statuses
        uses: gardarik/provider-status-action@develop
        with:
          providers: |
            aws.cloudfront
            aws.apigateway-us-east-1
            aws.lambda-us-east-1
            aws.route53privatedns-us-east-1
            mongodb
            auth0.749624
            auth0.1612668
            
  test-dev:
    runs-on: ubuntu-latest
    name: Testing dev
    steps:
      - name: Providers status
        uses: gardarik/provider-status-action@v1.0.0
        with:
          fail_on_warning: true
          providers: |
            aws.appstream2-us-east-1
            aws.apigateway-us-east-1
            aws.route53privatedns-us-east-1
            auth0.1612668
            mongodb
            mongodb.4343523

  test-main:
    runs-on: ubuntu-latest
    name: Testing Main
    steps:
      - name: Providers status
        uses: gardarik/provider-status-action@v1.0.3
        with:
          fail_on_warning: false
          providers: |
            aws.cloudfront
            aws.apigateway-us-east-1
            heroku
            heroku.apps
            aws.lambda-us-east-1
            datadog
            aws.route53privatedns-us-east-1
            mongodb
            auth0.749624
            auth0
            twilio
            atlassian
            newrelic
            pendo
            sendgrid
            cloudflare
            sentry
            hashicorp
            github
            snowflake
